default:
  image: php:latest

stages:
  - build
  - test

before_script:
  - ls
  - php -v

test_latest:
  stage: build
  script:
    - php -v
    - php toto.php

building:
  stage: build
  script:
    - echo "rien à compiler"

t0_latest:
  stage: test
  script:
    - php toto.php

t1_8-0-12:
  stage: test
  image: php:8.0.12-cli
  script:
    - php toto.php


